openapi: 3.0.0
info:
  title: GitHub's v3 REST API.
  description: The GitHub API is a REST API used to access GitHub's features.
  version: 0.0.0
tags:
  - name: meta
  - name: gists
paths:
  /:
    get:
      tags:
        - meta
      operationId: meta/root
      description: Get Hypermedia links to resources accessible in GitHub's REST API
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RootModel'
  /gists:
    get:
      tags:
        - gists
      operationId: list/gists
      summary: List gists for the authenticated user
      description: '"Lists the authenticated user''s gists or if called anonymously, this endpoint returns all public gists:"'
      parameters:
        - $ref: '#/components/parameters/SinceParameter'
        - $ref: '#/components/parameters/PerPageParameter'
        - $ref: '#/components/parameters/PageParameter'
      responses:
        '200':
          description: The request has succeeded.
          headers:
            link:
              required: true
              schema:
                type: string
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BaseGist'
    post:
      tags:
        - gists
      operationId: create/gist
      summary: Create a gist
      description: Allows you to add a new gist with one or more files.\n\n**Note:** Don't name your files \"gistfile\" with a numerical suffix. This is the format of the automatic naming scheme that Gist uses internally.
      parameters: []
      responses:
        '201':
          description: The request has succeeded and a new resource has been created as a result.
          headers:
            location:
              required: true
              schema:
                type: string
                format: uri
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseGist'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateGistRequest'
components:
  parameters:
    PageParameter:
      name: page
      in: query
      required: false
      description: The page number of the results to fetch. For more information, see [Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).
      schema:
        type: integer
        format: int32
        default: 1
    PerPageParameter:
      name: per_page
      in: query
      required: false
      description: The number of results per page (max 100). For more information, see [Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).
      schema:
        type: integer
        format: int32
        default: 30
    SinceParameter:
      name: since
      in: query
      required: false
      description: 'Only show results that were last updated after the given time. This is a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ`.'
      schema:
        type: string
        format: date-time
  schemas:
    BaseGist:
      type: object
      required:
        - url
        - forks_url
        - commits_url
        - id
        - node_id
        - git_pull_url
        - git_push_url
        - html_url
        - files
        - public
        - created_at
        - updated_at
        - description
        - comments
        - comments_url
        - owner
        - truncated
        - forks
        - history
      properties:
        url:
          type: string
          format: uri
        forks_url:
          type: string
          format: uri
        commits_url:
          type: string
          format: uri
        id:
          type: string
        node_id:
          type: string
        git_pull_url:
          type: string
          format: uri
        git_push_url:
          type: string
          format: uri
        html_url:
          type: string
          format: uri
        files:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/GistFile'
        public:
          type: boolean
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        description:
          type: string
        comments:
          type: integer
          format: int32
        user:
          $ref: '#/components/schemas/SimpleUser'
        comments_url:
          type: string
          format: uri
        owner:
          $ref: '#/components/schemas/SimpleUser'
        truncated:
          type: boolean
        forks:
          type: array
          items: {}
        history:
          type: array
          items: {}
      description: Base Gist
    CreateGistRequest:
      type: object
      required:
        - files
      properties:
        description:
          type: string
          description: Description of the gist
        public:
          type: boolean
          description: Flag indicating whether the gist is public
          default: false
        files:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/GistContent'
          description: Names and content for the files that make up the gist
    GistContent:
      type: object
      required:
        - content
      properties:
        content:
          type: string
    GistFile:
      type: object
      required:
        - filename
        - type
        - language
        - raw_url
        - size
      properties:
        filename:
          type: string
        type:
          type: string
        language:
          type: string
        raw_url:
          type: string
          format: uri
        size:
          type: integer
          format: int32
    LinkResponseHeader:
      type: object
    LocationResponseHeader:
      type: object
    RootModel:
      type: object
      required:
        - current_user_url
        - current_user_authorizations_html_url
        - authorizations_url
        - code_search_url
        - commit_search_url
        - emails_url
        - emojis_url
        - events_url
        - feeds_url
        - followers_url
        - following_url
        - gists_url
        - hub_url
        - issue_search_url
        - issues_url
        - keys_url
        - notifications_url
        - organization_url
        - organization_repositories_url
        - organization_teams_url
        - public_gists_url
        - rate_limit_url
        - repository_url
        - repository_search_url
        - current_user_repositories_url
        - starred_url
        - starred_gists_url
        - topic_search_url
        - user_url
        - user_organizations_url
        - user_repositories_url
        - user_search_url
      properties:
        current_user_url:
          type: string
          format: uri
        current_user_authorizations_html_url:
          type: string
          format: uri
        authorizations_url:
          type: string
          format: uri
        code_search_url:
          type: string
          format: uri
        commit_search_url:
          type: string
          format: uri
        emails_url:
          type: string
          format: uri
        emojis_url:
          type: string
          format: uri
        events_url:
          type: string
          format: uri
        feeds_url:
          type: string
          format: uri
        followers_url:
          type: string
          format: uri
        following_url:
          type: string
          format: uri
        gists_url:
          type: string
          format: uri
        hub_url:
          type: string
          format: uri
        issue_search_url:
          type: string
          format: uri
        issues_url:
          type: string
          format: uri
        keys_url:
          type: string
          format: uri
        notifications_url:
          type: string
          format: uri
        organization_url:
          type: string
          format: uri
        organization_repositories_url:
          type: string
          format: uri
        organization_teams_url:
          type: string
          format: uri
        public_gists_url:
          type: string
          format: uri
        rate_limit_url:
          type: string
          format: uri
        repository_url:
          type: string
          format: uri
        repository_search_url:
          type: string
          format: uri
        current_user_repositories_url:
          type: string
          format: uri
        starred_url:
          type: string
          format: uri
        starred_gists_url:
          type: string
          format: uri
        topic_search_url:
          type: string
          format: uri
        user_url:
          type: string
          format: uri
        user_organizations_url:
          type: string
          format: uri
        user_repositories_url:
          type: string
          format: uri
        user_search_url:
          type: string
          format: uri
    SimpleUser:
      type: object
      required:
        - login
        - id
        - node_id
        - avatar_url
        - url
        - html_url
        - followers_url
        - following_url
        - gists_url
        - starred_url
        - subscriptions_url
        - organizations_url
        - repos_url
        - events_url
        - received_events_url
        - type
        - site_admin
        - starred_at
      properties:
        name:
          type: string
        email:
          type: string
        login:
          type: string
        id:
          type: integer
          format: int32
        node_id:
          type: string
        avatar_url:
          type: string
          format: uri
        gravatar_id:
          type: string
        url:
          type: string
          format: uri
        html_url:
          type: string
          format: uri
        followers_url:
          type: string
          format: uri
        following_url:
          type: string
          format: uri
        gists_url:
          type: string
          format: uri
        starred_url:
          type: string
          format: uri
        subscriptions_url:
          type: string
          format: uri
        organizations_url:
          type: string
          format: uri
        repos_url:
          type: string
          format: uri
        events_url:
          type: string
          format: uri
        received_events_url:
          type: string
          format: uri
        type:
          type: string
        site_admin:
          type: boolean
        starred_at:
          type: string
          format: date-time
      description: Simple User
servers:
  - url: https://api.github.com
    description: GitHub API
    variables: {}
